"""
Data download script for OceanEmbed.

Connects to Copernicus Marine Environment Monitoring Service (CMEMS)
to download requested datasets for the target region and time period.

Supports generating synthetic NetCDF files if CMEMS is unavailable or
credentials are not configured.

Usage:
    python scripts/download_data.py --mock
"""

import argparse
import os
import sys
from datetime import datetime, timedelta

import numpy as np
import xarray as xr

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ml.constants import DOMAIN, NUM_DEPTHS, STANDARD_DEPTHS, NUM_INPUT_CHANNELS


def generate_mock_netcdf(output_dir: str, dataset_type: str, domain: dict, n_days: int = 30):
    """
    Generate synthetic NetCDF files for testing the pipeline when CMEMS is unavailable.
    """
    print(f"Generating mock {dataset_type} dataset...")
    
    # Create coordinate arrays
    lons = np.arange(domain['lon_min'], domain['lon_max'] + 0.25, 0.25)
    lats = np.arange(domain['lat_min'], domain['lat_max'] + 0.25, 0.25)
    times = [datetime(2023, 1, 1) + timedelta(days=i) for i in range(n_days)]
    
    H = len(lats)
    W = len(lons)
    T = len(times)
    
    # 2D Grid for spatial correlations
    lons_2d, lats_2d = np.meshgrid(lons, lats)
    
    if dataset_type == "surface":
        # Realistic spatial distributions
        # SST: warmer near equator (30) dropping to 20 at latitude 30
        base_sst = 30.0 - (lats_2d - 5.0) * 0.4
        # SSS: River runoff (Ganges/Brahmaputra) makes north less saline
        base_sss = 35.0 - (lats_2d - 5.0) * 0.1
        # SSH: Eddies generated by sin/cos functions
        base_ssh = 0.5 * np.sin(lons_2d * 0.5) * np.cos(lats_2d * 0.5)
        # Currents & Winds: Gyre patterns
        base_u = 0.5 * np.sin(lats_2d * 0.2)
        base_v = 0.5 * np.cos(lons_2d * 0.2)
        
        sst = np.tile(base_sst, (T, 1, 1)) + np.random.randn(T, H, W) * 0.2
        sss = np.tile(base_sss, (T, 1, 1)) + np.random.randn(T, H, W) * 0.1
        ssh = np.tile(base_ssh, (T, 1, 1)) + np.random.randn(T, H, W) * 0.05
        u = np.tile(base_u, (T, 1, 1)) + np.random.randn(T, H, W) * 0.05
        v = np.tile(base_v, (T, 1, 1)) + np.random.randn(T, H, W) * 0.05
        wind_u = u * 10 + np.random.randn(T, H, W) * 1.0
        wind_v = v * 10 + np.random.randn(T, H, W) * 1.0

        data_vars = {
            'sst': (['time', 'lat', 'lon'], sst),
            'sss': (['time', 'lat', 'lon'], sss),
            'ssh': (['time', 'lat', 'lon'], ssh),
            'u': (['time', 'lat', 'lon'], u),
            'v': (['time', 'lat', 'lon'], v),
            'wind_u': (['time', 'lat', 'lon'], wind_u),
            'wind_v': (['time', 'lat', 'lon'], wind_v),
        }
        filename = "mock_surface_data.nc"
        
    elif dataset_type == "subsurface":
        depths = STANDARD_DEPTHS
        D = len(depths)
        
        temp_data = np.zeros((T, D, H, W))
        base_sst = 30.0 - (lats_2d - 5.0) * 0.4
        thermocline_depth = 50.0 + (lats_2d - 5.0) * 2.0 + 10.0 * np.sin(lons_2d * 0.5)
        
        for i, d in enumerate(depths):
            # Logistic decay to deep water temp (4.0)
            decay = 1 / (1 + np.exp((d - thermocline_depth) / 40.0))
            layer_temp = 4.0 + (base_sst - 4.0) * decay
            temp_data[:, i, :, :] = np.tile(layer_temp, (T, 1, 1)) + np.random.randn(T, H, W) * 0.1
            
        data_vars = {
            'thetao': (['time', 'depth', 'lat', 'lon'], temp_data)
        }
        
        filename = "mock_subsurface_data.nc"
        
    else:
        raise ValueError(f"Unknown mock dataset type: {dataset_type}")
        
    # Create xarray dataset
    coords = {
        'time': times,
        'lat': lats,
        'lon': lons,
    }
    
    if dataset_type == "subsurface":
        coords['depth'] = depths
        
    ds = xr.Dataset(data_vars=data_vars, coords=coords)
    
    # Save to file
    filepath = os.path.join(output_dir, filename)
    ds.to_netcdf(filepath)
    print(f"Saved mock dataset to {filepath}")
    return filepath


def download_cmems_data(config_name: str, output_dir: str):
    """
    Actual CMEMS download logic using copernicusmarine client.
    Requires credentials.
    """
    import yaml
    
    config_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'configs', 'datasets.yaml')
    with open(config_path, 'r') as f:
        datasets_config = yaml.safe_load(f).get('datasets', {})
        
    if config_name not in datasets_config:
        print(f"ERROR: Dataset '{config_name}' not found in datasets.yaml")
        return False
        
    ds_config = datasets_config[config_name]
    dataset_id = ds_config.get('dataset_id')
    variables = list(ds_config.get('variable_mapping', {}).keys())
    
    print(f"\nAttempting to download {config_name} from CMEMS...")
    print(f"Dataset ID: {dataset_id}")
    print(f"Variables: {variables}")
    
    try:
        import copernicusmarine
    except ImportError:
        print("ERROR: copernicusmarine package is not installed.")
        print("Run with --mock to generate synthetic data for testing.")
        return False
        
    print("Checking CMEMS credentials...")
    try:
        copernicusmarine.login()
        
        # Bay of Bengal Jan 2022 subset
        print(f"Downloading Bay of Bengal subset for Jan 2022...")
        
        # We specify minimum necessary parameters to prevent downloading globally.
        copernicusmarine.subset(
            dataset_id=dataset_id,
            variables=variables,
            minimum_longitude=80.0,
            maximum_longitude=95.0,
            minimum_latitude=10.0,
            maximum_latitude=20.0,
            start_datetime="2022-01-01T00:00:00",
            end_datetime="2022-01-31T23:59:59",
            minimum_depth=0.0,
            maximum_depth=1000.0,
            output_directory=output_dir,
            output_filename=f"{config_name}_bob_jan2022.nc",
            force_download=True
        )
        print(f"✅ Successfully downloaded {config_name} subset to {output_dir}")
        return True
    except Exception as e:
        print(f"❌ CMEMS Authentication or download failed: {e}")
        print("Please configure your credentials using 'copernicusmarine login'")
        return False


def main():
    parser = argparse.ArgumentParser(description="Download Ocean Data")
    parser.add_argument("--mock", action="store_true", help="Generate synthetic NetCDF files instead of downloading")
    parser.add_argument("--dataset", choices=["glorys", "ostia", "smos", "altimetry", "ascat", "globcurrent", "all"], default="all", help="Which dataset to download (default: all)")
    parser.add_argument("--output", default="data/raw", help="Output directory")
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)
    
    if args.mock:
        print("Running in MOCK mode. Generating synthetic NetCDF files.")
        generate_mock_netcdf(args.output, "surface", DOMAIN)
        generate_mock_netcdf(args.output, "subsurface", DOMAIN)
        print("\nDataset generation complete.")
        print(f"Files saved in: {os.path.abspath(args.output)}")
    else:
        datasets_to_download = ["glorys", "ostia", "smos", "altimetry", "ascat", "globcurrent"] if args.dataset == "all" else [args.dataset]
        
        for ds in datasets_to_download:
            success = download_cmems_data(ds, args.output)
            if not success:
                print(f"\n[BLOCKER] Failed to download {ds}. Cannot proceed with real data pipeline.")
                print("Make sure COPERNICUSMARINE_SERVICE_USERNAME and COPERNICUSMARINE_SERVICE_PASSWORD are set.")
                sys.exit(1)
        print("\nAll requested datasets downloaded successfully.")

if __name__ == "__main__":
    main()
