"""
Preprocess raw ocean data into harmonized format.

Usage:
    python scripts/preprocess.py
"""

import argparse
import os
import sys

import yaml
import numpy as np
import xarray as xr

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ml.data.adapters.cmems import CMEMSAdapter
from ml.data.quality import run_quality_control
from ml.data.harmonizer import harmonize_dataset
from ml.data.missing_data import handle_missing_data
from ml.constants import DOMAIN, STANDARD_DEPTHS


def process_surface_data(raw_path: str, output_path: str):
    print("\n--- Processing Surface Data ---")
    config = {"dataset_id": "cmems_surface", "product_id": "surface_obs"}
    adapter = CMEMSAdapter("surface", config=config)
    ds = adapter.load(raw_path)
    print(f"Loaded variables: {list(ds.data_vars)}")
    
    # Coordinate Normalization
    print("Normalizing coordinates...")
    
    # Harmonization (Explicit spatial regridding to 0.25 degree)
    print("Harmonizing (subset, spatial regrid, resample)...")
    ds = harmonize_dataset(ds, domain=DOMAIN, resolution=0.25)
    
    # Missing data handling
    print("Handling missing data...")
    for var in ds.data_vars:
        data = ds[var].values
        # Fill missing values spatially
        filled, mask = handle_missing_data(data, method='spatial')
        ds[var].values = filled
        # Add mask variable
        ds[f"{var}_mask"] = (ds[var].dims, mask)
        
    ds.to_netcdf(output_path)
    print(f"Saved harmonized surface data to {output_path}")


def process_subsurface_data(raw_path: str, output_path: str):
    print("\n--- Processing Subsurface Target Data ---")
    config = {"dataset_id": "cmems_mod_glo_phy_my_0.083_P1D-m", "product_id": "GLOBAL_MULTIYEAR_PHY_001_030"}
    adapter = CMEMSAdapter("glorys", config=config)
    ds = adapter.load(raw_path)
    print(f"Loaded variables: {list(ds.data_vars)}")
    
    # Coordinate Normalization
    print("Normalizing coordinates...")
    
    # Harmonization (Spatial regridding to 0.25 degree)
    print("Harmonizing spatial grid...")
    ds = harmonize_dataset(ds, domain=DOMAIN, resolution=0.25)
    
    # Explicit Depth Interpolation to canonical 15 depths
    print("Regridding/Interpolating to 15 standard depths...")
    if 'depth' in ds.coords:
        # Interpolate along depth dimension
        ds = ds.interp(depth=STANDARD_DEPTHS, method='linear', kwargs={"fill_value": "extrapolate"})
    
    # Missing data handling
    print("Handling missing data...")
    for var in ds.data_vars:
        if var == 'thetao' or var == 'target_temp':
            data = ds[var].values
            filled, mask = handle_missing_data(data, method='spatial')
            ds[var].values = filled
            ds[f"{var}_mask"] = (ds[var].dims, mask)
            
    ds.to_netcdf(output_path)
    print(f"Saved harmonized subsurface data to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Preprocess ocean data")
    parser.add_argument("--raw-dir", default="data/raw")
    parser.add_argument("--output-dir", default="data/processed")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    
    # Here we assume download_data.py has saved a combined surface NetCDF and a glorys NetCDF
    # For a real pipeline, each raw file might need to be processed and merged.
    surface_raw = os.path.join(args.raw_dir, "surface_merged_jan2022.nc") # To be generated by a merge script if multiple files
    subsurface_raw = os.path.join(args.raw_dir, "glorys_bob_jan2022.nc")
    
    surface_out = os.path.join(args.output_dir, "harmonized_surface.nc")
    subsurface_out = os.path.join(args.output_dir, "harmonized_subsurface.nc")
    
    if not os.path.exists(surface_raw) or not os.path.exists(subsurface_raw):
        print(f"[BLOCKER] Raw data files missing in {args.raw_dir}")
        print("Required: surface_merged_jan2022.nc and glorys_bob_jan2022.nc")
        sys.exit(1)
        
    process_surface_data(surface_raw, surface_out)
    process_subsurface_data(subsurface_raw, subsurface_out)
    
    print("\nPreprocessing complete.")


if __name__ == "__main__":
    main()
